0 constant _RETURN
1 constant _ADD
2 constant _SUBTRACT
3 constant _DOWN
4 constant _UP
5 constant _HOME
6 constant _END
7 constant _PGDN
8 constant _PGUP
9 constant _Ins
10 constant _Del
11 constant _Multiply
12 constant _Divide
20 constant Ctrl_RETURN
21 constant Ctrl_ADD
22 constant Ctrl_SUBTRACT
23 constant Ctrl_DOWN
24 constant Ctrl_UP
25 constant Ctrl_HOME
26 constant Ctrl_END
27 constant Ctrl_PGDN
28 constant Ctrl_PGUP
29 constant Ctrl_Ins
30 constant Ctrl_Del
31 constant Ctrl_Multiply
32 constant Ctrl_Divide
40 constant Shift_RETURN
41 constant Shift_ADD
42 constant Shift_SUBTRACT
43 constant Shift_DOWN
44 constant Shift_UP
45 constant Shift_HOME
46 constant Shift_END
47 constant Shift_PGDN
48 constant Shift_PGUP
49 constant Shift_Ins
50 constant Shift_Del
51 Constant Shift_Multiply
52 constant Shift_Divide
60 constant Alt_RETURN
69 constant Alt_Ins
61 constant Alt_ADD
62 constant Alt_SUBTRACT
71 constant Alt_Multiply
72 constant Alt_Divide
83 constant Ctrl_C
115 constant Alt_S
116 constant Alt_T
121 constant Alt_Y

